## library() calls go here
library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)
library(tidyverse)
library(readxl)
library(here)
library(janitor)
library(conflicted)
library(lubridate)
library(lme4)
library(rmarkdown)
library(broom)
library(broom.mixed)
library(vegan)
library(RVAideMemoire)
library(patchwork)
library(scales)
library(ggplot2)
library(cowplot)
library(grid)
library(gtable)
library(ggplotify)
library(emmeans)
library(ggpubr)
library(ggrepel)
library(glue)
library(ggpmisc)
library(car)
library(performance)

conflict_prefer("lag", "dplyr")
conflict_prefer("filter", "dplyr")

